version: '3.9'

services:

  php:
    build: ./php
    container_name: php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - elasticsearch
      - redis
    networks:
      - magento-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - magento-net

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - magento-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - mysql
    networks:
      - magento-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - magento-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    networks:
      - magento-net

  varnish:
    image: varnish:latest
    container_name: varnish
    ports:
      - "6081:6081"
    depends_on:
      - nginx
    command: >
      varnishd -F -a :6081 -b nginx:80
    networks:
      - magento-net

volumes:
  mysql-data:

networks:
  magento-net:
